--- #YAML:1.0
name:               Apache-Hadoop-Watcher
version:            0.01
abstract:           Perl extension for Hadoop Monitoring
author:
    - Snehasis Sinha <snehasis@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:      2.124
    IO::Socket::INET:  1.31
    JSON:              2.15
    LWP::UserAgent:    5.833
    XML::Twig:         3.34
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
